use_frameworks!

target 'OreOre_Example' do
  pod 'OreOre', :path => '../'

  target 'OreOre_ExampleUITests' do
    inherit! :search_paths

    pod 'Apollo'
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
